### ISSUE TITLE
Getting "Couldn't connect to server" error

### ISSUE THREAD

**Issue by Fairydx** [Art-of-WiFi/UniFi-API-client#207] opened 2023-12-18 16:21 UTC
Good afternoon,

I'm experiencing an error after upgrading my UDM to version v3.2.7. When attempting to log in to the API, I receive the following error message. I have already updated the API Client to the latest version from this repository.

Please find the error below.

```
{
  "message": "cURL error: Failed to connect to x.x.x.x port 8443 after 0 ms: Couldn't connect to server",
  "exception": "ErrorException",
  "file": "/var/www/html/captive.controlink.pt/vendor/art-of-wifi/unifi-api-client/src/Client.php",
  "line": 154,
  "trace": [
    {
      "file": "/var/www/html/captive.controlink.pt/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",
      "line": 254,
      "function": "handleError",
      "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
      "type": "->"
    },
    {
      "function": "Illuminate\\Foundation\\Bootstrap\\{closure}",
      "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
      "type": "->"
    },
    {
      "file": "/var/www/html/captive.controlink.pt/vendor/art-of-wifi/unifi-api-client/src/Client.php",
      "line": 154,
      "function": "trigger_error"
    },
    {
      "file": "/var/www/html/captive.controlink.pt/app/Http/Controllers/StoresController.php",
      "line": 170,
      "function": "login",
      "class": "UniFi_API\\Client",
      "type": "->"
    }
}
```

Can you help me with this?

Best regards,
Fairydx

**Comment by Fairydx** [comment] 2023-12-18 17:07
I have this configured on my Port Forward options:
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/8240478/88681ba1-2d83-47b1-aeb3-90898117a337)

**Comment by malle-pietje** [comment] 2023-12-18 17:15
Okay, but the "Couldn't connect to server" suggested something is wrong at the TCP level. We also use the API client in Laravel (up to version 10) stacks and don't see such errors. Here's an entry from one of our apps:
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/12016131/f5c64bfb-e422-4a11-940c-faef48164bdd)

**Comment by malle-pietje** [comment] 2023-12-18 17:17
Wait, did you not create a specific firewall rule to allow access to port 443 (local) from the WAN interface? In that case, please follow these instructions:
https://artofwifi.net/blog/how-to-access-the-unifi-controller-by-wan-ip-or-hostname-on-a-udm-pro

**Comment by Fairydx** [comment] 2023-12-18 18:06
I have that enabled.

![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/8240478/d97487be-2026-4b85-8b9d-ec84a637be4d)

Should I need to create a specific firewall rule for the 8443 port?

**Comment by Fairydx** [comment] 2023-12-18 18:11
I'm seeing now that I can't even disable the Remote Direct Access feature.
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/8240478/ca4b30e6-1b6d-4fc4-9dbc-1597a38f7b58)

However I'm using a WAN IP address on the UDM:
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/8240478/8281900d-5945-4349-a1ca-b1e6898aebf0)

**Comment by malle-pietje** [comment] 2023-12-18 20:06
Something is not set up correctly with your firewall rules. I can’t reproduce this here.

**Comment by malle-pietje** [comment] 2023-12-18 20:09
> I have that enabled.
> 
> ![image](https://private-user-images.githubusercontent.com/8240478/291370670-d97487be-2026-4b85-8b9d-ec84a637be4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzAwNjIsIm5iZiI6MTcwMjkyOTc2MiwicGF0aCI6Ii84MjQwNDc4LzI5MTM3MDY3MC1kOTc0ODdiZS0yMDI2LTRiODUtOGI5ZC1lYzg0YTYzN2JlNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMjAwMjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjVkYzZiODIyN2I3MzlhYjcyYWRhMjFkMjdkMjgyM2JjNTA1MTZjYzMxZDY5NWFmYThhOTdkYTAzMGU5MmJmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VMoGN3-eh4Aiqs535f87muytAULfqNy5yWbn-YGcEQ0)
> 
> Should I need to create a specific firewall rule for the 8443 port?

No, simply create a firewall based on the second method described in that blog post. You might consider creating a backup and resetting the unit to factory defaults…

**Comment by Fairydx** [comment] 2023-12-21 09:58
I'm having the same problem with all the versions of unifi management on the web, I have a server that has the Unifi Management installed to connect to old ubiquiti devices, and I have the same error here.. I believe that this is not a device problem, because if I try to connect via API in another device, it works fine.

Do you know what can be blocking the connection?

**Comment by malle-pietje** [comment] 2023-12-21 10:58
I'm afraid this issue is unrelated to the API client package. I recommend opening a topic on the Ubiquiti community forums instead. It helps if you can validate the issues by simply trying to connect to the web interface of your UniFi OS console from the "outside".

This might be related to the "Direct Remote Connection" feature which is greyed out but Ubiquiti would need to confirm that.

I will close this issue for now, please re-open it again in case it becomes clear the issue is related to the API client.

**Closed by malle-pietje** 2023-12-21 10:58 UTC

**Comment by Fairydx** [comment] 2023-12-21 13:37
This is not related with a device itself, it's related with the connection between my server and the ubiquiti devices.

It's not only one device it's all of them

**Comment by malle-pietje** [comment] 2023-12-21 15:00
I'm afraid I cannot reproduce this at all.

**Comment by Fairydx** [comment] 2023-12-22 09:44
I moved the captive portal to another server, and this problem goes away.
If you know any way to understand or debug what is going on with the server, please share it.

**Comment by malle-pietje** [comment] 2023-12-22 10:48
There are so many things that can affect the connectivity... One thing to check is whether the server is running Selinux. This can block outgoing connections.
